-- VERSION = $Id$
INSERT INTO team
(id, abbr, location, name)
VALUES
( 1,'ari','Arizona','Cardinals'),
( 2,'atl','Atlanta','Falcons'),
( 3,'bal','Baltimore','Ravens'),
( 4,'buf','Buffalo','Bills'),
( 5,'car','Carolina','Panthers'),
( 6,'chi','Chicago','Bears'),
( 7,'cin','Cincinnati','Bengals'),
( 8,'cle','Cleveland','Browns'),
( 9,'dal','Dallas','Cowboys'),
(10,'den','Denver','Broncos'),
(11,'det','Detroit','Lions'),
(12, 'gb','Green Bay','Packers'),
(13,'hou','Houston','Texans'),
(14,'ind','Indianapolis','Colts'),
(15,'jac','Jacksonville','Jaguars'),
(16, 'kc','Kansas City','Chiefs'),
(17,'mia','Miami','Dolphins'),
(18,'min','Minnesota','Vikings'),
(19, 'ne','New England','Patriots'),
(20, 'no','New Orleans','Saints'),
(21,'nyg','N.Y. Giants','Giants'),
(22,'nyj','N.Y. Jets','Jets'),
(23,'oak','Oakland','Raiders'),
(24,'phi','Philadelphia','Eagles'),
(25,'pit','Pittsburgh','Steelers'),
(26,'stl','St. Louis','Rams'),
(27, 'sd','San Diego','Chargers'),
(28, 'sf','San Francisco','49ers'),
(29,'sea','Seattle','Seahawks'),
(30, 'tb','Tampa Bay','Buccaneers'),
(31,'ten','Tennessee','Titans'),
(32,'was','Washington','Redskins');
